### ISSUE TITLE
not responsive (menu disappears)

### ISSUE THREAD

**Issue by erik55** [xupefei/Travelify#2]
The top menu disappears if you use the theme on a small screen. Well, not the menu, but the text which in the Sample is
* Welcome
* Category 1
* Category 2

When I use other responsive designs, the menu is converted to a button which has all the buttons/texts inside.

Any hint on that?

**Comment by xupefei** [comment]
This theme is currently not well-fitted for small screens, and I plan to fix this issue in few weeks. If you would like to fix it by yourself, see https://css-tricks.com/convert-menu-to-dropdown/.

**Comment by erik55** [comment]
Ok, thanks for your response. I’d really like to fix it. But that will
be in two months (end of August).

Thanks for your great work!

Paddy Xu schrieb am 28.06.2017 um 21:37:
